### ISSUE TITLE
error with reference class field ‘Ut’, should be from class “dgCMatrix”

### ISSUE THREAD

**Issue by marisalver** [variani/lme4qtl#1]
Thank you for providing a method for analysis! I am using lme4qtl for a linear mixed model analysis, but I keep getting an error:

Error: invalid assignment for reference class field ‘Ut’, should be from class “dgCMatrix” or a subclass (was class “dgeMatrix”)

Do you have any suggestions where that might stem from?

This is how I got the kinship matrix:

library("Matrix")
library("lme4")
maatriks2=read.csv("table.txt", sep=" ", dec=".", header=TRUE,stringsAsFactors=FALSE)
class(maatriks2[,1])
class(maatriks2)
dim(maatriks2)
rownames(maatriks2) = maatriks2[,1]
maatriks2[,1]=NULL

maatriks2<-as.matrix(maatriks2)
maatriks2=as(maatriks2,"dgCMatrix”)

mudel2 <- relmatLmer(CTG_LDL_statin ~ Age+ Sugu + (1|Vcode1), FH2, relmat = list(Vcode1 = maatriks2))

**Comment by variani** [comment]
Based on the data your shared with me by emai, I see that the matrix is not symmetric.

```
library(Matrix)

isSymmetric(maatriks2, tol = 0)
#[1] FALSE

isSymmetric(maatriks2, tol = 0.01)
#[1] FALSE

isSymmetric(maatriks2, tol = 0.02)
#[1] TRUE
```

Hence, the error comes from either EVD or Cholesky decomposition from the Matrix R package. 

I would suggest to "symmetrize" your matrix (I am not sure what is the best way to do it) and pass clean input to `relmatLmer`.

**Comment by marisalver** [comment]
Hey

Thank you for the quick feedback. Yes, the asymmetry was the problem with the small dataset (n=100). But I cannot get it working with 1000 individuals, the same error occurs.

Maris

**Comment by marisalver** [comment]
Hey

I attached an .Rdata file with maatriks2 and FH2 (n=100) that works and maatriks3 and FH3 (n=200) that gives the same error. Both of the matrices (maatrik2 and maatriks3) are symmetrical. I retrieved these matrices from the same original data file with the sample command.

Maris

**Comment by marisalver** [comment]
Hey

It turned out that the error occurred as some eigenvalues were negative in the matrix as the n increased. We used nearPD to get an approximation and that new matrix worked and I got my estimates.

Thanks so much for the package and help!

Maris

**Comment by variani** [comment]
Hi Maris,

It is good to know your solution based on nearPD! Thanks for sharing.

It might be a general suggestion to do some checks on your relationship matrix  (is symmetric, EVD ok?) before calling `relmatLmer`.

In future versions, I am thinking to add option passing the relationship matrix in two formats, matrix and its EVD. So, the user has more controls.

Best,
Andrey

**Comment by variani** [comment]
Take care of those relationship matrices needing `nearPD`:

- write a test on synthetic data
- output informative warning
- fix the issue inside the package (so there is no need to apply `nearPD` outside)

**Comment by variani** [comment]
The class conversion error (the title of this thread) seems to be fixed with the last commit and bumped version 0.1.11. 

Though, it doesn't rule out related issues when the custom covariance is poorly defined that leads to convergence failure, etc
