### ISSUE TITLE
Family data, genetic variant

### ISSUE THREAD

**Issue by Tubahy** [variani/lme4qtl#10]
Hi!

I’m not familiar with the analysis of quantitative traits with family data.  There are data on individuals from two extended families including several generations. Of these individuals, about 50% are carriers of a specific mutation (genetic variant).  It is already known that a particular disease develops in the carriers, but it is of interest to evaluate the effect of this genetic variant on some traits associated with this disease. The phenotype variable, let's call it **pheno**, is normally distributed, and among individuals (**id**) there are both carriers and non-carriers of the genetic variant (a binary variable **gvar**). In addition, there are several other explanatory variables, such as **sex** and **age**.  It's essential to account for family relationships, and it seems that lme4qtl package offers a solution. However, it is not entirely clear to me whether it is possible to model the effect of a single genetic variant with the lme4qtl package and how to proceed with the analysis. Below are some specific questions: 

-  How the data on family relationships (i.e. family tree, several generations) should be coded? Probably some generation identifier (**genid**, 0,1,2,3,4) and/or family or sibling identifier?

- What kind of custom covariance matrices should be used with the data described above? 

- How to model (or account for) the gene-environment effects, such as the shared environmental effect for siblings (**sibid**)?

And more generally, what are essential things to take into account when using lme4qtl package?

**Comment by variani** [comment]
Hi,

It seems you have general questions, not exactly specific to `lme4qtl`. So, let me share some links you might find useful.

-1) The standard way is to have 3 ID fields: individual ID, father ID and mother ID (two IDs more for the case of twins). The R package [kinship2](https://cran.r-project.org/web/packages/kinship2/index.html) can be the first resource here.

I also estimated matrices using SOLAR and my previously developed R package [solarius](https://github.com/ugcd/solarius). Here it is the [tutorial](http://ugcd.github.io/solarius/vignettes/tutorial.html) with some examples.

-2) In [Supplementary Material](https://static-content.springer.com/esm/art%3A10.1186%2Fs12859-018-2057-x/MediaObjects/12859_2018_2057_MOESM1_ESM.pdf) of our published paper (Supplementary Note 3), you can find a way how to compute genetic relationship matrices (additive and dominant) on pedigree data.

-3) Any grouping ID variable such as `sibid` is used to construct a random effect using `(1|sibid)` syntax in the R formula interface for mixed models (supported by `lme4`).

You can browse other issues here to get an idea about strenths and limitations of `lme4qtl`.

Good luck with your project!

**Comment by variani** [comment]
I close this issue. Feel free to re-open it if you have new related questions. Thanks.
