### ISSUE TITLE
Error about kinship matrix

### ISSUE THREAD

**Issue by JulongWei** [variani/lme4qtl#11]
Dear Dr. Ziyatdinov,
Thanks for your providing a very friendly-user interface to achieve LMM on the R platform.
Some errors happened when providing kinship matrix, like the following,

**lmm0 <- relmatLmer(y~1+Pilot+Year+Breed+(1|ID),data=d,relmat=list(ID=mykin),REML=TRUE)
invalid assignment for reference class field ‘Ut’, should be from class “dgCMatrix” or a subclass (was class “dgeMatrix”)**

Best,
Julong

**Comment by JulongWei** [comment]
Hi,
The issues has been reported before.
But isSymmetric(kk) is TRUE. So, what's the problem?
Best,
Julong

**Comment by variani** [comment]
Hi Julong,

In the same issue #1 you mentioned, the author of the question suggested to use `Matrix::nearPD` function to prepare the custom covariance matrix. You might want to read the help `?Matrix::nearPD` for further details.

I still need to think how to control "bad input" matrices. To be updated in issue #1 sometime.

**Comment by variani** [comment]
I close this issue. Please follow updates in issue #1.
