### ISSUE TITLE
General doubts & ideas to improve 'lme4qtl'

### ISSUE THREAD

**Issue by mvazquezs** [variani/lme4qtl#12]
I am going to apply  ```relmatLmer()``` to evaluate the effect of age (center and continuous variable), sex and height in others. I have some doubts:

* How is the best way to evaluate the covariates in  ```relmatLmer()```: model with additive effects or interaction of covariates.

```r
relmatLmer(var ~ AGE_gr + AGEc + SEXc + height + (1 | ID), data = dat, relmat = list(id  = dat_id))
relmatLmer(var ~ AGE_gr * AGEc + AGE_gr * SEXc + AGE_gr * height + (1 | ID), data = dat, relmat = list(id  = dat_id))
```

*  In case that the additive model contains ```NAs``` in covariates (e.g. height), ```drop1``` function does not evaluate the significance by any test.
```r
Error in drop1.merMod(model) : 
  number of rows in use has changed: remove missing values?
```

* There are any option to evaluate the significance of the covariates with ```NAs```? The significance test could be included into model ```summary()``` as ```glm()``` allowed?

Any solution available?

Thanks in advance.

**Comment by variani** [comment]
Hi!

I added the [script](https://github.com/variani/lme4qtl/blob/master/misc/issues/12/01-replicate-error.R) that replicates your error with `anova` and proposes a solution using `subset`.

I am not sure whether other specific libraries such as [lmerTest](https://cran.r-project.org/web/packages/lmerTest/index.html) or [afex](https://github.com/singmann/afex) have a more elegant way to deal with this annoying `number of rows in use has changed: remove missing values?`. 

Let me know if you find any alternatives to my ad-hoc solution in the script.

**Comment by variani** [comment]
Going back to your first question about "evaluate covariates", the following help page `help("pvalues", package = "lme4")` is the first reference. Also, googling gives many other references and discussions.

For a specific analysis like a simple GWAS with a single (genetic) random effect, researchers use the Wald test converting Z-score to chi-squared statistic. Again, using Z-score as a test statistic is not suggested in general for mixed models, but it can work under certain scenarios.

**Comment by mvazquezs** [comment]
Hi!

I've been tested some options to evaluate the statistical significance of the effect of covariates in the ```relmatLmer()``` function. I think that the best solution to obtain a detailed ```summary()``` is to use ```Anova()``` function of the ```library(car)```. For the platelet count model, as follow

```r
mod <- relmatLmer(plt ~ AGE_gr * AGEc  +  AGE_gr * SEXc  +  (1|ID), dat, list(id = dat_id))
```

The summary reports as follow:

```r
car::Anova(mod, type = 'II', test.statistic = 'F'))

Analysis of Deviance Table (Type II Wald F tests with Kenward-Roger df)

Response: plt
                  F Df Df.res    Pr(>F)    
AGE_gr      36.3259  1    360 4.133e-09 ***
AGEc        11.0278  1    360 0.0009894 ***
SEXc        18.4224  1    360 2.278e-05 ***
AGE_gr:AGEc 25.0756  1    360 8.650e-07 ***
AGE_gr:SEXc  0.0841  1    360 0.7719302    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

Thanks in advance.

**Comment by variani** [comment]
I think this Anova solution is ok, as it doesn’t refit the model (the risky part of the lme4qtl package). 

I close the issue then. Thanks
