### ISSUE TITLE
"direct" test of SNP in relmatGlmer / relmatLmer

### ISSUE THREAD

**Issue by danfulop** [variani/lme4qtl#15]
Hi @variani,

I was looking at your Demo code and wondering why you don't include the SNP as another term in the `relmatLmer()` model and test association to the SNP directly from the lme4qtl model fit?  You could do so via `anova()` (against a null model without the SNP) or with lmerTest, unless I'm missing something.

Also, for relmatGlmer the `$coefficients` from the model fit include a p-value for the SNP, so there's no need to use add-on packages there.

I'm hoping you can enlighten by pointing out the flaws in my argument 😄 

Thanks!
Dan.

**Comment by variani** [comment]
Hi Dan,

You are right proposing `anova` for association testing. That's a computationally acceptable choice when your sample size is not greater than 1K and relationship matrix is sparse (the latter is lme4-specific).

When one has a dataset of 10-100K individuals and 1-10M SNPs to test, a different approach under simplified assumptions is required, i.e. that described in [gwas demo](https://github.com/variani/lme4qtl/blob/master/demo/gwas.R).

So, go with `anova` if your analysis is fast.

I hope I answered your question.

**Comment by danfulop** [comment]
Thanks a ton for the informative response!  Yes, the current dataset is small enough that it works okay, although it could be faster.
