### ISSUE TITLE
Remove effect of the modeled VCV (e.g., pedigree) from the expected values of y

### ISSUE THREAD

**Issue by johannesbjork** [variani/lme4qtl#16]
I want to remove the effect of the the modeled VCV matrix (e.g., pedigree) from the expected values of `y`.

Say that I run `fit <- lme4qtl::relmatLmer(y ~  time + (1 | ID) + group, data = dat, relmat = list(ID = ID_VCV))` and `y_exp <- predict(fit)` to get the expected values. How can I then remove the effect of the modeled VCV from `y_exp`?

Does `fit@resp$mu` correspond to `u` in Equation 1 from the paper? 

If so, in order to remove the effect of the modeled VCV from the expected values, could I simply subtract `fit@resp$mu` from `y_exp`? 

Thanks,
Johannes

**Comment by variani** [comment]
I guess you need to see the help page `?predict.merMod` and check the argument `re.form`. I added some code here [01-predict.R](https://github.com/variani/lme4qtl/blob/master/misc/issues/16/01-predict.R).

The code for your example might look like:

```
y_hat_fixed <- predict(fit, re.form = NA)
```

I remember myself googling it when I first came with the same question, and `re.form = NA` syntax was not very intuitive to me.
