### ISSUE TITLE
way to adjust for kinship only?

### ISSUE THREAD

**Issue by complexgenome** [variani/lme4qtl#21]
Hello there,

Is there a way I can only adjust for kinship and not any random effect when using lme4qtl? My model would be as:

`output <- relmatGlmer(trait ~ age + sex, data, relmat = list(ID = kin2), family = binomial(logit))
`

**Comment by variani** [comment]
You are missing `(1|ID)` term in your formula, all the rest is fine.

You can also check an example below on `dat40` dataset.

```r
library(lme4qtl)
data(dat40, package = "lme4qtl")

output <- relmatGlmer(trait1bin ~ AGE + SEX + (1|ID), dat40, 
  relmat = list(ID = kin2), family = binomial(logit))
```

**Comment by complexgenome** [comment]
I'd not like to adjust for familial ID as random effect, but only kinship. If I adjust for both then I'm over-fitting the model. 
I'm trying to replicate findings from another tool (GEMMA), so was wondering.

**Comment by variani** [comment]
I am not sure I fully understand your comment.

The model I wrote has a single random effect `(1|ID)` linked to the kinship matrix through `relmat` argument. If you call houshold/family/etc grouping effect as "familial ID", which is `(1|FAMID)`, then it is not present in the model.  

Does it address your question?
