### ISSUE TITLE
Details of the Eigenvalue decomposition operation

### ISSUE THREAD

**Issue by hl-anna** [variani/lme4qtl#22]
An additional file to your paper about _lme4qtl_ mentions that _lme4qtl_ is able to deal with a low-rank random effect covariance matrix by replacing _Cholesky decomposition_ by the _Eigenvalue decomposition operation._ Unfortunately, I was not able to find details about how this method works anywhere.In case you are able to provide me with any details or relevant sources where I could learn more about this I would highly appreciate it.

**Comment by variani** [comment]
Hi,

You are right that only Cholesky decomposition is outlined with the formula in our article. I added an example [R code](https://github.com/variani/lme4qtl/blob/master/misc/issues/22/cov-decomp.R) with Cholesky and EVD decomposition. Basically, decompositions looks as following:

```
K is a symmetric covariance matrix (input)

Cholesky:
K = L L'  = R'R

EVD:
K = V D V'
R = D^{0.5} V'

Matrices R in Cholesy and EVD are the same for full-rank K, while Cholesky fails for low-rank K.
```

Let me know if you have any further questions.
