### ISSUE TITLE
Multiple matrices as random effects

### ISSUE THREAD

**Issue by msohail88** [variani/lme4qtl#23]
Dear Dr. Ziyatdinov,

Thank you for making lme4qtl. I am writing with a question. Is it possible with lme4qtl to fit random effects for two matrices. Say in my model, I am interested in fitting a random effect for not only the kinship matrix, but also a second matrix of pairwise distances.

In a simple example, extending that from your software page, my understanding is that I could fit a second matrix as follows.

```
library(lme4)
library(lattice)
library(lme4qtl)

data(dat40, package = "lme4qtl")
m1 <- relmatLmer(trait1 ~ AGE + SEX + (1|FAMID) + (1|ID), dat40, relmat = list(ID = kin2))

# make new matrix
K = kin2 * kin2
dat40$ID2 <- dat40$ID

m2 <- relmatLmer(trait1 ~ AGE + SEX + (1|FAMID) + (1|ID) + (1|ID2), dat40, relmat = list(ID = kin2, ID2=K))

```
Could you please confirm that this would work as I expect?
A second question if you could confirm the following - say the IDs in the rownames of the kinship matrix and in the ID variable of the dat40 dataframe have an overlapping set but are not exactly the same (one is a subset of the other). Do I understand correctly that that the overlapping set of IDs will be subsetted in the relmatLmer function automatically, and that is the set the mixed model will be run on?

Lastly, when modeling something like gender or FAMID, do you recommend keeping the variable type as "chr" instead of "factor" or does it make no difference?

Many thanks in advance,

Mashaal Sohail

**Comment by variani** [comment]
Hi Mashaal,

A short answer will be "yes", but I need to check use cases you are asking with formal tests. 

Best,
Andrey

**Comment by variani** [comment]
I added a few tests that cover your questions about input format of covariance matrices.

I couldn't find cases when using factors instead of characters for ID variables makes any difference. Perhaps, something might go wrong when calling `predict` function. Please let me know if you find such cases.
