### ISSUE TITLE
ICC or h2 for binary response.

### ISSUE THREAD

**Issue by lmorozcor** [variani/lme4qtl#24]
I have been working with the `lme4qtl` package, I have a binary response database, in README indicates that you can work for a binary response (which is my problem) but I need the ICC (Intraclass Correlation coefficient) especially the h2 for binary data with family data structure. Using `lme4qtl::VarProp` I do not get the desired h2 since the `prop` value is 1, could you help me how I can find h2 for binary response data with family structure please?

**Comment by variani** [comment]
I think this question is general to `lme4`, and here is one reference, http://bbolker.github.io/mixedmodels-misc/glmmFAQ.html. I am aware of methods to estimate the heritability (h2) for binary outcomes in my field of research ([link](http://www.nealelab.is/blog/2017/9/13/heritability-201-types-of-heritability-and-how-we-estimate-it)), but I am not sure about [ICC](https://stats.stackexchange.com/questions/62770/calculating-icc-for-random-effects-logistic-regression).

Of note, I created `lme4qtl::VarProp` to use for quantitative outcomes in my analyses and never tried it with binary outcomes.
