### ISSUE TITLE
Use matlm for interaction between dependent variable and SNP

### ISSUE THREAD

**Issue by DesmondSmith** [variani/lme4qtl#29]
Dear Andrey,

I followed your tutorial (https://github.com/variani/lme4qtl/blob/master/demo/gwas.R) using matlm to rapidly run lme4qtl using precalculated variance components. It was, indeed, very fast.

Is it possible to use a similar strategy to quickly run a mixed model that evaluates the significant of an interaction between a SNP and a condition? 

For example, matlm::matlm(trait1 ~ HEIGHT * SNP1, dat40, pred = gdat40, ids = ids, transform = W, 
  batch_size = 100, verbose = 2), 

where HEIGHT = short or tall, and SNP1 = 0 or 1. I would like P vals for the effect of SNP1 (and SNP2, SNP3, etc) on trait1 in short people as well as tall people, and also the P val for the interaction.

Based on your comments in the code for matlm, you are working on this issue, but I thought there would be no harm in asking.

Thank you very much!

**Comment by variani** [comment]
Hi,

[matlm](https://github.com/variani/matlm) is a separate package from lme4qtl, and matlm is something I used to build custom GWAS mixed models for my manuscripts. One shouldn't expect much support of code based on matlm.

Luckily, I have an example of code for interaction analysis that seems relevant to your question: [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7171162/), [code](https://gist.github.com/variani/a28c18797c39a62bacab587e6e708529).

I would suggest to give it a try on some simulated data to check it fits your expectations. Then run it for your target application on your own risk.

Indeed, the math of the mixed-model test is not that complicated once you get V = var(y). At modest sample sizes, it can be implemented even using base R functions.

Hope it helps.
Andrey

**Comment by DesmondSmith** [comment]
Thanks very much, Andrey! -- cheers, Des
