### ISSUE TITLE
cannot coerce type 'closure' to vector of type 'character'

### ISSUE THREAD

**Issue by opain** [variani/lme4qtl#31]
Hello,

Thanks again for developing this very useful package. I am encountering the following error:

(1) model continiuous trait `trait1`
	mod <- relmatLmer(trait1 ~ AGE + SEX + (1|FAMID) + (1|ID), dat40, relmat = list(ID = kin2))
	Error in as.character(sys.call(sys.parent())[[1L]]) :
			cannot coerce type 'closure' to vector of type 'character'

I have attached the conda environment I am working in when I get the error. I don't get the error when I try running the same analysis  using R 3.6.0.

[GenoFunc.yaml.txt](https://github.com/variani/lme4qtl/files/8078939/GenoFunc.yaml.txt)

Have you encountered this error before or noticed any issue when using R 4.0.2?

Many thanks,

Ollie

**Comment by variani** [comment]
Hi Oliver,

Thank you for using `lme4qtl` (and citing it!).

I've checked your code example on a newly installed version of `lme4qtl` (the current version v0.2.2) and it works (R version 4.1.2). 

Is there something related to conda? The conda has an earlier version of `lme4qtl` (version?), but I don't think I made major updates between the two versions. Contact the person who maintains `lme4qtl` in conda?

I can also update the code in [relmatLmer.R](https://github.com/variani/lme4qtl/blob/master/R/relmatLmer.R) and make the internal `relmat_lmer` function to be `relmatLmer`. Again, somebody needs to update the conda version of the package.

Best,
Andrey

**Comment by opain** [comment]
Dear Andrey,

Many thanks for your quick and clear reply. You are right that this issue seems to be due to the version within my conda environment. I thought I had checked this - apologies, I must have still been testing the conda version of lme4qtl. I have now removed lme4qtl from the conda environment, and install it directly from github, and I no longer receive the error. 

I am not very familiar with the conda community and don't know how to update the version provided by bioconda. Apologies for not being able to help here. It says online that this is done automatically but this doesn't seem to have worked. Hopefully this issue will highlight any issues for other users using the package through conda.

Nonetheless, the error is no longer occurring for me so please feel free close my issue.

Many thanks,

Ollie
