### ISSUE TITLE
Predicting new data/unobserved phenotypes

### ISSUE THREAD

**Issue by rtassinari** [variani/lme4qtl#33]
Dear Variani, thanks a lot for your useful package,

I would like to know if there is a way, perhaps through the `ranef()`function, to predict genotypes that are in the kinship matrix, but have not been phenotyped, usually the parental ones, or new combinations, for example:

![pedigree_scheme](https://user-images.githubusercontent.com/100167662/199745384-a9b69a95-e8ab-4794-b289-236ccbeade20.png)

```
fitA<- relmatLmer(y~ rep + (x1 | ID), data=phe,
                relmat= list(ID=A), REML=T)
ranef(fitA)
$ID
   (Intercept)        x1
P1    ?
P2    ?
P3    ?
P4    ?
X1   -4.174645  3.869076
X2   -1.354763  1.255599
X3   -1.301316  1.206064
X4    1.264602 -1.172037
X5    ?
```

This naïve exemple files:
[A.txt](https://github.com/variani/lme4qtl/files/9930048/A.txt)
[pedigree.txt](https://github.com/variani/lme4qtl/files/9930049/pedigree.txt)
[pheno.txt](https://github.com/variani/lme4qtl/files/9930050/pheno.txt)

Thank you very much!

**Comment by variani** [comment]
Hi,

I'm not sure I fully get your question. Your model can be used to predict phenotypes using genotypes. I can't see how genotypes can be inferred via the model.

I guess you might be interested to check works like [this article](https://www.nature.com/articles/s41467-022-34383-6), but that is not related to the lme4 model in your post.

That is my quick reply. Sorry I cannot be of much help.

Best,
Andrey
