### ISSUE TITLE
GRM matrix constraints 

### ISSUE THREAD

**Issue by rbutleriii** [variani/lme4qtl#37]
Hi @variani , quick question about the range of values for the genetic relationship matrix. I am doing an association of plasma biomarkers to a plasma proteomic dataset (SomaLogic), and am adjusting for relatedness using [PCrelate](https://bioconductor.org/packages/devel/bioc/vignettes/GENESIS/inst/doc/pcair.html#output-from-pc-relate) in the GENESIS package to generate my GRM. As noted in the demo and one [issue](https://github.com/UW-GAC/GENESIS/issues/56), the distribution of the k0 estimates means that the diagonal of my matrix will have some values greater than 1. Is that going to be an issue with `lme4qtl`? should I be attempting with the unscaled kinship matrix instead?

**Comment by variani** [comment]
Hi Robert,

There is not any limitations on the relationship matrix as long as EVD of it is computable. You can get EVD outside lme4qtl to check your GRM is computationally fine.

If you scale your GRM by a scalar, that would simply mean that you scale the variance explained by GRM, i.e., the variance component or sigma^2 parameter associated with the GRM. 

Hope this helps.

Best,
Andrey
