### ISSUE TITLE
help documentation

### ISSUE THREAD

**Issue by calebglossrex** [variani/lme4qtl#4]
Hi there, 

I was wondering if there would be more of an expansion of the help documentation in the future. In particular, I'm wondering how the covariance matrix should be coded/structured and am having trouble figuring that out based on the information available. I have played with some of the sample data sets, but still am uncertain as to how to proceed.

Thanks so much.

**Comment by variani** [comment]
Hi,

Adding more documentation is not a priority right now. The [preprint](https://www.biorxiv.org/content/early/2017/08/31/139816) together with supplementary material and [vignette](https://github.com/variani/lme4qtl/blob/master/vignettes/pedigreemm.Rmd) is the best place to see code examples and explanations.

My hope is that lme4 users can easily run lme4qtl. 

Let me know if you have any specific question.

Best,
Andrey

**Comment by calebglossrex** [comment]
Hi Andrey,

Thank you so much for the prompt reply. My apologies for the delayed
response, I must have missed this email.

I was trying to run the relmatLmer function using a matrix I coded for the
relmat = list(myID = myMatrix)) argument. Specifically, I'm working with
family data and the covariance matrix I coded is a symmetric matrix of the
genetic relatedness between the subjects in the sample (MZ twins = 1, DZ
twins and full siblings = 0.5, half-siblings = 0.25, and unrelated subjects
= 0). However, when I enter this matrix in lieu of myMatrix, the error is
the folowing




I'm certain my matrix is symmetric so that error doesn't quite make sense.

I also noticed that the matrix (kin2) you use in your toy data set (dat40)
​is a Sparse matrix, so I made my matrix a sparse matrix to see if that
would help. Still no dice, same error.

I'm wondering what you might suggest.

Thanks.

Best,
Briana

**Comment by variani** [comment]
Hi Briana,

I can't see the error messages in your previous post. Could you send this info. again? Also, it would be helpful to have a reproducible example, e.g., on simulated data.

Based on description of your data (the kinship matrix), I don't see any reason why `relmatLmer` would not work.

Best,
Andrey
