### ISSUE TITLE
relmatGlmer slow

### ISSUE THREAD

**Issue by FinSalMar** [variani/lme4qtl#8]
Hi,

I am trying to use the relmatGlmer function to model a binary response variable with two fixed effects and one random effect using ~16,000 individuals. The random effect is a genomic relationship matrix with the 16,000 individuals. 

i.e. relmatGlmer(
  myBinaryTrait ~ myCovariate1 + myCovariate2 + (1|myID), 
  myData, 
  relmat = list(myID = myMatrix),
  family = binomial
)

It seems to be running very slow. Should this be a problem with this number of individuals? Or is the cause of it running slowly likely something else? Also, is there a recommended way to format the relationship matrix so that is runs more quickly?

Thanks.

**Comment by variani** [comment]
Hi,

You question is similar to the issue #2. Please see the discussion there. Also, we addressed this question in our article.

The only format of relationship matrices supported by lme4qtl is Matrix, which is due to dependency on lme4. Let me know if you have any further questions.
